---
- hosts: localhost
  gather_facts: True

  pre_tasks:
    - include_vars: vars.yml
      tags: ["always"]

    - name: Checkout shell-env
      ansible.builtin.git:
        repo: 'https://github.com/laidbackware/shell-env.git'
        dest: "{{ ansible_env.HOME }}/.shell-env"

    - name: Ensuring Homebrew Is Installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Installing Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists


    # - name: Create the temporary directory
    #   tempfile:
    #     state: directory
    #     suffix: setup
    #   register: temp_dir_results
    #   tags: ["pre"]

    # - set_fact:
    #     temp_dir={{ temp_dir_results.path }}
    #   tags: ["pre"]

  vars:
    home_dir: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"

  roles:
    - role: system/virt-shared-subnet
      tags: ["virt-subnet"]

    - role: dev/git-setup
      tags: ["git-setup"]

    - role: homebrew
      tags: ["homebrew"]
    
    - role: asdf/install
      tags: ["asdf-install"]

    # - role: apps/vscode
    #   when: desktop_mode or laptop_mode or chromebook_mode
    #   tags: ["vscode"]
      
    # - role: apps/hyper
    #   when: desktop_mode or laptop_mode or chromebook_mode
    #   tags: ["hyper"]

    # - role: fonts
    #   tags: ["fonts"]

    # - role: shell/starship
    #   tags: ["starship"]

    - role: shell/zshrc
      tags: ["shell-zshrc", "shell"]


  # post_tasks:
  #   - name: Remove the temporary directory
  #     file:
  #       path: "{{ temp_dir }}"
  #       state: absent
    
