---
- hosts: localhost
  gather_facts: True

  pre_tasks:
    - include_vars: vars.yml
      tags: ["always"]

    # - name: Create the temporary directory
    #   tempfile:
    #     state: directory
    #     suffix: setup
    #   register: temp_dir_results
    #   tags: ["pre"]

    # - set_fact:
    #     temp_dir={{ temp_dir_results.path }}
    #   tags: ["pre"]

  vars:
    home_dir: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"

  roles:
    - role: system/virt-shared-subnet
      tags: ["virt-subnet"]

    - role: dev/git-setup
      tags: ["git-setup"]

    # - role: shell/aliases
    #   tags: ["shell-aliases", "shell"]

    # - role: shell/completion
    #   tags: ["shell-completion", "shell"]

    # - role: shell/functions
    #   tags: ["shell-functions", "shell"]
    
    # - role: asdf/install
    #   tags: ["asdf-install"]

    # - role: apps/vscode
    #   when: desktop_mode or laptop_mode or chromebook_mode
    #   tags: ["vscode"]
      
    # - role: apps/hyper
    #   when: desktop_mode or laptop_mode or chromebook_mode
    #   tags: ["hyper"]

    # - role: fonts
    #   tags: ["fonts"]

    # - role: shell/starship
    #   tags: ["starship"]

    # - role: shell/bashrc
    #   tags: ["shell-bashrc", "shell"]


  # post_tasks:
  #   - name: Remove the temporary directory
  #     file:
  #       path: "{{ temp_dir }}"
  #       state: absent
    
